apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  labels:
    app: python-application
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-application
 
  template:
    metadata:
      name: python-redis
      labels:
        app: python-application
   
  spec:
    containers:
      - name: python-redis
        image: abosaeed/python-docker
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config